### PR TITLE
more virtual keyboard layouts, more fonts in deps.

### PR DESCRIPTION
**Pull request by norayr**
added fonts as dependencies.
added more virtual keyboard layouts.

### CODE REVIEW

**Comment by freemangordon** [comment]
Are those new layouts registered in gconf?

**Comment by norayr** [comment]
> Are those new layouts registered in gconf?

i don't even know what does it mean.
how can i check?
they are available in the text input applet and it is possible to write using them.

**Comment by freemangordon** [comment]
> > Are those new layouts registered in gconf?
> 
> i don't even know what does it mean.
> how can i check?
> they are available in the text input applet and it is possible to write using them.

Yes, that was the answer I was waiting for :) .

**Comment by MerlijnWajer** [comment]
Building now for `maemo/beowulf-devel`

**Pull request merged**
