### PR TITLE
Fix scv width

### PR DESCRIPTION
**Pull request by MerlijnWajer**
image

### CODE REVIEW

**Comment by MerlijnWajer** [comment]
@freemangordon - please review

**Comment by MerlijnWajer** [comment]
Not sure how/if this would work on portrait mode, btw.

**Comment by freemangordon** [comment]
looks good, merging

**Comment by MerlijnWajer** [comment]
Thanks, tagging and building now.

**Comment by freemangordon** [comment]
> Not sure how/if this would work on portrait mode, btw.

I guess it depends on the resolution, but it is not different to "main" VKB imo

**Pull request merged**
